# allows to use local package folders if versions are within range, fetch from npm if not
linkWorkspacePackages: true

packages:
  - canton-connect
  - canton-dappbooster
  - canton-theme
  - dapp/daml
  - dapp/frontend

allowBuilds:
  '@bootnodedev/canton-wallet-service@https://codeload.github.com/BootNodeDev/canton-wallet-service/tar.gz/d14ee9838986ca1f33c5eae204af54d70fbb55fd': true
  esbuild: true
  protobufjs: true
  puppeteer: false
